### ISSUE TITLE
can it make tinymce editor autogrow?

### ISSUE THREAD

**Issue by wakaryry** [jevin/Autogrow-Textarea#13]
can it make tinymce editor autogrow?

I tried. But it seems not.

**Comment by jevin** [comment]
Nopes. The plugin does not support TinyMCE. If your mind is not set on TinyMCE you can try CKEditor. They have an autogrow plugin: http://ckeditor.com/addon/autogrow

**Comment by wakaryry** [comment]
Thanks much. It really helps me.
